Repository AY2425S1-CS2113-T11-2/tp, pull requests merged in 2024-10, with the labels that each got.

#2 Added a scanner for user inputs
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Flashbang.java
Labels: type.Task

#16 Skeleton Code for main and Parser
  src/main/java/seedu/duke/Flashbang.java
  src/main/java/seedu/duke/flashutils/commands/AddCommand.java
  src/main/java/seedu/duke/flashutils/commands/Command.java
  src/main/java/seedu/duke/flashutils/commands/InvalidCommand.java
  src/main/java/seedu/duke/flashutils/commands/ViewCommand.java
  src/main/java/seedu/duke/flashutils/types/FlashBook.java
  src/main/java/seedu/duke/flashutils/types/FlashCard.java
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
  src/main/java/seedu/duke/flashutils/utils/Parser.java
  src/main/java/seedu/duke/flashutils/utils/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, type.Task, priority.High

#25 Fix bug with adding Cards to FlashBook, Add saving Cards to a txt file and Add JUnit Test for Storage
  build.gradle
  src/main/java/seedu/duke/Flashbang.java
  src/main/java/seedu/duke/flashutils/commands/AddCommand.java
  src/main/java/seedu/duke/flashutils/commands/Command.java
  src/main/java/seedu/duke/flashutils/commands/DeleteCommand.java
  src/main/java/seedu/duke/flashutils/commands/EditCommand.java
  src/main/java/seedu/duke/flashutils/commands/FlashbangCommand.java
  src/main/java/seedu/duke/flashutils/commands/InvalidCommand.java
  src/main/java/seedu/duke/flashutils/commands/QuitCommand.java
  src/main/java/seedu/duke/flashutils/commands/ViewCommand.java
  src/main/java/seedu/duke/flashutils/types/FlashBook.java
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
  src/main/java/seedu/duke/flashutils/utils/Storage.java
  src/test/java/seedu/duke/flashutils/utils/StorageTest.java
Labels: type.Task, type.Bug, priority.Medium, severity.High

#32 fix typo in Ui
  src/main/java/seedu/duke/flashutils/utils/Ui.java
Labels: type.Bug

#55 Add Style.puml
  docs/diagrams/ParsingSequenceDiagram.puml
  docs/diagrams/Style.puml
Labels: type.Task

#52 Show flashbang percentage
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
Labels: priority.High

#56 Add non design portions of the Developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#63 Added more unit testing for AddCommand
  src/main/java/seedu/duke/flashutils/commands/AddCommand.java
  src/test/java/seedu/duke/flashutils/commands/AddCommandTest.java
Labels: priority.High
