Repository AY2425S1-CS2113-T11-2/tp, pull requests merged in 2024-11, with the labels that each got.

#64 Added unit testing for DeleteComand
  src/test/java/seedu/duke/flashutils/commands/DeleteCommandTest.java
Labels: priority.High

#74 Fix code to be in line with checkstyle configuration
  data/SampleModule.txt
  src/main/java/seedu/duke/flashutils/commands/EditCommand.java
  src/main/java/seedu/duke/flashutils/commands/FlashbangCommand.java
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
  src/main/java/seedu/duke/flashutils/utils/Parser.java
  src/test/java/seedu/duke/FlashbangTest.java
  src/test/java/seedu/duke/flashutils/commands/AddCommandTest.java
  src/test/java/seedu/duke/flashutils/commands/DeleteCommandTest.java
  src/test/java/seedu/duke/flashutils/commands/EditCommandTest.java
  src/test/java/seedu/duke/flashutils/commands/QuitCommandTest.java
  src/test/java/seedu/duke/flashutils/commands/ViewCommandTest.java
  src/test/java/seedu/duke/flashutils/utils/ParserTest.java
  src/test/java/seedu/duke/flashutils/utils/StorageTest.java
Labels: type.Task

#59 Add parser component section in the DG
  docs/DeveloperGuide.md
  docs/diagrams/ParsingSequenceDiagram.png
  docs/diagrams/ParsingSequenceDiagram.puml
Labels: type.Task

#77 Implemented viewing of mistakes after flashbang
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
Labels: priority.High

#82 Add Developer Guide PDF
  build.gradle
  data/FunModule.txt
  data/SampleModule.txt
  docs/Developer Guide _ tp.pdf
Labels: type.Task, priority.High

#146 Fix major command issues
  src/main/java/seedu/duke/Flashbang.java
  src/main/java/seedu/duke/flashutils/commands/AddCommand.java
  src/main/java/seedu/duke/flashutils/commands/Command.java
  src/main/java/seedu/duke/flashutils/commands/DeleteCommand.java
  src/main/java/seedu/duke/flashutils/commands/EditCommand.java
  src/main/java/seedu/duke/flashutils/commands/FlashbangCommand.java
  src/main/java/seedu/duke/flashutils/commands/InvalidCommand.java
  src/main/java/seedu/duke/flashutils/commands/QuitCommand.java
  src/main/java/seedu/duke/flashutils/commands/ViewAllCommand.java
  src/main/java/seedu/duke/flashutils/commands/ViewCommand.java
  src/main/java/seedu/duke/flashutils/types/FlashCardSet.java
  src/main/java/seedu/duke/flashutils/utils/Ui.java
Labels: priority.High

#160 Update UserGuide.md and UML diagrams for UI class
  docs/UserGuide.md
  docs/diagrams/UIClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task

#171 Add search command
  docs/UserGuide.md
  src/main/java/seedu/duke/Flashbang.java
  src/main/java/seedu/duke/flashutils/commands/SearchCommand.java
  src/main/java/seedu/duke/flashutils/types/Card.java
  src/main/java/seedu/duke/flashutils/utils/Parser.java
Labels: type.Story, priority.High

#163 Create PPP - angelinawong1210.md
  docs/team/angelinawong1210.md
Labels: type.Task

#179 Invalid module input for the Add Command
  src/main/java/seedu/duke/flashutils/commands/AddCommand.java
  src/main/java/seedu/duke/flashutils/utils/Parser.java
Labels: severity.Medium
